### ISSUE TITLE
How to get result from "utilities.Printer()"?

### ISSUE THREAD

**Issue by sw-dev-code** [Nagasaki45/watson-streaming#17]
Hi @Nagasaki45, 

First, I want to thank you and congratulate on the job you've done.

Can you give me advice on how to get the result from `utilities.Printer()`?
From the main script (similar to your example) I want to pass the result to Watson Assistant.

Thank you in advance.

**Comment by Nagasaki45** [comment]
Hi @Milan991! Thanks for reaching out. You probably don't need the `utilities.Printer`, but a custom `fluteline.Consumer` that will process the results as they arrive from IBM Watson. Your consumer should look similar to this:

```python
class MilansConsumer(fluteline.Consumer):
    def consume(self, item):
        # Do something with the item
```

Then swap the printer with `MilansConsumer`.

Hope it's clear. If not feel free to ask again.

Cheers,
Tom

**Comment by Nagasaki45** [comment]
Closing for now. You're welcome to reopen if still have questions.

**Comment by sw-dev-code** [comment]
Sorry, I was suppose to close it earIier. I was able to solve it, thanks once again.

**Comment by Nagasaki45** [comment]
Sure! You're more than welcome :-)
